# Generated by Django 6.0 on 2025-12-09 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='업체명')),
                ('contract_desc', models.TextField(blank=True, verbose_name='계약내용')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=200, verbose_name='도메인')),
                ('admin_url', models.CharField(blank=True, max_length=200, verbose_name='관리자 URL')),
                ('admin_id', models.CharField(blank=True, max_length=100, verbose_name='관리자 ID')),
                ('admin_pw', models.CharField(blank=True, max_length=100, verbose_name='관리자 PW')),
                ('hosting_company', models.CharField(blank=True, max_length=100, verbose_name='호스팅 업체')),
                ('hosting_expire_at', models.DateField(blank=True, null=True, verbose_name='호스팅 만료일')),
                ('domain_registrar', models.CharField(blank=True, max_length=100, verbose_name='도메인 등록처')),
                ('domain_expire_at', models.DateField(blank=True, null=True, verbose_name='도메인 만료일')),
                ('memo', models.TextField(blank=True, verbose_name='사이트 메모')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='직급')),
                ('team', models.CharField(blank=True, max_length=50, verbose_name='팀/부서')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='전화번호')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='요청 업무')),
                ('description', models.TextField(blank=True, verbose_name='요청 상세')),
                ('status', models.CharField(choices=[('OPEN', '진행 전'), ('DOING', '진행 중'), ('DONE', '완료')], default='OPEN', max_length=10, verbose_name='상태')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.company')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='담당자')),
            ],
        ),
    ]
