# Generated by Django 6.0 on 2025-12-09 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='일정 제목')),
                ('description', models.TextField(blank=True, verbose_name='상세 내용')),
                ('start_at', models.DateTimeField(verbose_name='시작 일시')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 일시')),
                ('event_type', models.CharField(choices=[('GENERAL', '일반'), ('COMPANY', '업체 관련'), ('MEETING', '회의'), ('LEAVE', '연차/휴가')], default='GENERAL', max_length=20, verbose_name='종류')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.company', verbose_name='관련 업체')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='등록한 사용자')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.employee', verbose_name='관련 직원')),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정 목록',
                'ordering': ['-start_at'],
            },
        ),
    ]
