# Generated by Django 6.0 on 2025-12-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_calendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='일정 제목'),
        ),
    ]
