# Generated by Django 6.0 on 2025-12-09 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_calendarevent_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '업체', 'verbose_name_plural': '업체 목록'},
        ),
        migrations.AlterModelOptions(
            name='companyrequest',
            options={'verbose_name': '요청사항', 'verbose_name_plural': '요청사항 목록'},
        ),
        migrations.AlterModelOptions(
            name='companysite',
            options={'verbose_name': '업체 사이트', 'verbose_name_plural': '업체 사이트 목록'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '직원', 'verbose_name_plural': '직원 목록'},
        ),
        migrations.CreateModel(
            name='CompanyMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='메모 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='core.company', verbose_name='업체')),
            ],
            options={
                'verbose_name': '업체 메모',
                'verbose_name_plural': '업체 메모 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
