# Generated by Django 6.0 on 2025-12-09 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_options_alter_companyrequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contract_desc',
        ),
        migrations.CreateModel(
            name='CompanyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='태그')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.company', verbose_name='업체')),
            ],
            options={
                'verbose_name': '업체 태그',
                'verbose_name_plural': '업체 태그 목록',
                'ordering': ['name'],
            },
        ),
    ]
