# Generated by Django 6.0 on 2025-12-10 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_company_contract_desc_companytag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='팀명')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
            ],
            options={
                'verbose_name': '팀',
                'verbose_name_plural': '팀 목록',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.team', verbose_name='팀/부서'),
        ),
    ]
